/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-10-20 17:19:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.includes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sideBar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    <div class=\"app-sidebar__overlay\" data-toggle=\"sidebar\"></div>\r\n");
      out.write("    <aside class=\"app-sidebar\">\r\n");
      out.write("      <div class=\"app-sidebar__user\"><img class=\"app-sidebar__user-avatar\" src=\"https://s3.amazonaws.com/uifaces/faces/twitter/jsa/48.jpg\" alt=\"User Image\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <p class=\"app-sidebar__user-name\">John Doe</p>\r\n");
      out.write("          <p class=\"app-sidebar__user-designation\">Frontend Developer</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <ul class=\"app-menu\">\r\n");
      out.write("        <li><a class=\"app-menu__item\" href=\"dashboard.html\"><i class=\"app-menu__icon fa fa-dashboard\"></i><span class=\"app-menu__label\">Dashboard</span></a></li>\r\n");
      out.write("        <li class=\"treeview\"><a class=\"app-menu__item\" href=\"#\" data-toggle=\"treeview\"><i class=\"app-menu__icon fa fa-laptop\"></i><span class=\"app-menu__label\">UI Elements</span><i class=\"treeview-indicator fa fa-angle-right\"></i></a>\r\n");
      out.write("          <ul class=\"treeview-menu\">\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"bootstrap-components.html\"><i class=\"icon fa fa-circle-o\"></i> Bootstrap Elements</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"https://fontawesome.com/v4.7.0/icons/\" target=\"_blank\" rel=\"noopener\"><i class=\"icon fa fa-circle-o\"></i> Font Icons</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"ui-cards.html\"><i class=\"icon fa fa-circle-o\"></i> Cards</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"widgets.html\"><i class=\"icon fa fa-circle-o\"></i> Widgets</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a class=\"app-menu__item\" href=\"charts.html\"><i class=\"app-menu__icon fa fa-pie-chart\"></i><span class=\"app-menu__label\">Charts</span></a></li>\r\n");
      out.write("        <li class=\"treeview\"><a class=\"app-menu__item\" href=\"#\" data-toggle=\"treeview\"><i class=\"app-menu__icon fa fa-edit\"></i><span class=\"app-menu__label\">Forms</span><i class=\"treeview-indicator fa fa-angle-right\"></i></a>\r\n");
      out.write("          <ul class=\"treeview-menu\">\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"form-components.html\"><i class=\"icon fa fa-circle-o\"></i> Form Components</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"form-custom.html\"><i class=\"icon fa fa-circle-o\"></i> Custom Components</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"form-samples.html\"><i class=\"icon fa fa-circle-o\"></i> Form Samples</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"form-notifications.html\"><i class=\"icon fa fa-circle-o\"></i> Form Notifications</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"treeview\"><a class=\"app-menu__item\" href=\"#\" data-toggle=\"treeview\"><i class=\"app-menu__icon fa fa-th-list\"></i><span class=\"app-menu__label\">Tables</span><i class=\"treeview-indicator fa fa-angle-right\"></i></a>\r\n");
      out.write("          <ul class=\"treeview-menu\">\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"table-basic.html\"><i class=\"icon fa fa-circle-o\"></i> Basic Tables</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"table-data-table.html\"><i class=\"icon fa fa-circle-o\"></i> Data Tables</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"treeview is-expanded\"><a class=\"app-menu__item\" href=\"#\" data-toggle=\"treeview\"><i class=\"app-menu__icon fa fa-file-text\"></i><span class=\"app-menu__label\">Pages</span><i class=\"treeview-indicator fa fa-angle-right\"></i></a>\r\n");
      out.write("          <ul class=\"treeview-menu\">\r\n");
      out.write("            <li><a class=\"treeview-item active\" href=\"blank-page.html\"><i class=\"icon fa fa-circle-o\"></i> Blank Page</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"page-login.html\"><i class=\"icon fa fa-circle-o\"></i> Login Page</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"page-lockscreen.html\"><i class=\"icon fa fa-circle-o\"></i> Lockscreen Page</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"page-user.html\"><i class=\"icon fa fa-circle-o\"></i> User Page</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"page-invoice.html\"><i class=\"icon fa fa-circle-o\"></i> Invoice Page</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"page-calendar.html\"><i class=\"icon fa fa-circle-o\"></i> Calendar Page</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"page-mailbox.html\"><i class=\"icon fa fa-circle-o\"></i> Mailbox</a></li>\r\n");
      out.write("            <li><a class=\"treeview-item\" href=\"page-error.html\"><i class=\"icon fa fa-circle-o\"></i> Error Page</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a class=\"app-menu__item\" href=\"docs.html\"><i class=\"app-menu__icon fa fa-file-code-o\"></i><span class=\"app-menu__label\">Docs</span></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </aside>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
